server:
  port: 8090
  servlet:
    context-path: /kafka-producer

spring:
  kafka:
    producer:
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9093
      topic-name: kafka_example_movie_json
      properties:
        spring.json.add.type.headers: false
